---
# Role tasks

- name: setup fact with values loaded from host variables
  set_fact:
    "{{ select_hostvars_fact_name }}": >-
      {{ lookup('template', 'hostvars.yml.j2') | from_yaml }}
  tags:
    - role::select_hostvars
